name: Preview Deployment

env:
  VERCEL_ORG_ID: ${{secrets.VERCEL_ORG_ID}}
  VERCEL_PROJECT_ID: ${{secrets.VERCEL_PROJECT_ID}}

on:
  push:
    branches-ignore:
      - main 

jobs:
  production-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Project Dependencies
        run: npm ci

      - name: Install Dependencies for Vercel Deployment
        run: npm install --global vercel

      - name: Run ESLint
        run: npm run lint

      - name: Build Next.js app
        run: vercel pull --yes --environment=preview --token=${{secrets.VERCEL_TOKEN}}

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifcats
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}